name: checks

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup environment
      run: |
        echo Starting services
        sudo service mysql start

        echo Setting up
        sudo mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS branch;'

        echo Copying config files
        rm src/defaults.js
        cp test/config/workflow.js src/defaults.js
    - name: Install dependencies
      run: yarn
    - name: Lint
      run: yarn lint
    - name: Seed
      run: database_password=root yarn clean
    - name: Test
      run: database_password=root yarn test
