name: checks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup environment
      run: |
        mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS branch;'
    - name: Install dependencies
      run: yarn
    - name: Lint
      run: yarn lint
    - name: Seed
      run: yarn clean
    - name: Test
      run: yarn test
